/*
 * To change this template, choose Tools | Templates and open the template in
 * the editor.
 */
package com.kitfox.raven.editor.view.symbol;

import com.kitfox.raven.editor.NewDocumentWizard;
import com.kitfox.raven.editor.RavenDocument;
import com.kitfox.raven.editor.RavenDocumentEvent;
import com.kitfox.raven.editor.RavenDocumentListener;
import com.kitfox.raven.editor.RavenDocumentWeakListener;
import com.kitfox.raven.editor.RavenEditor;
import com.kitfox.raven.editor.RavenEditorListener;
import com.kitfox.raven.editor.RavenEditorWeakListener;
import com.kitfox.raven.editor.RavenSwingUtil;
import com.kitfox.raven.util.tree.NodeDocument;
import com.kitfox.raven.util.undo.History;
import com.kitfox.raven.util.undo.HistoryAction;
import com.kitfox.raven.wizard.RavenWizardDialog;
import java.awt.Color;
import java.awt.Component;
import java.util.EventObject;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.ListCellRenderer;
import javax.swing.SwingUtilities;
import javax.swing.UIDefaults;
import javax.swing.UIManager;

/**
 *
 * @author kitfox
 */
public class SymbolPanel extends javax.swing.JPanel
        implements RavenEditorListener, RavenDocumentListener
{
    final RavenEditor editor;
    RavenEditorWeakListener listenerEditor;
//    HistoryWeakListener listenerHistory;
    RavenDocumentWeakListener listenerRavenDoc;

    boolean updating;

    /**
     * Creates new form SymbolPanel
     */
    public SymbolPanel(RavenEditor editor)
    {
        this.editor = editor;
        
        initComponents();

//        list_symbols.setListData(new Object[]{"aaa", "bbb"});

        list_symbols.setCellRenderer(new Renderer());

        listenerEditor = new RavenEditorWeakListener(this, editor);
        editor.addRavenEditorListener(listenerEditor);
        
        updateDocument();
    }

    private void updateDocument()
    {
        if (listenerRavenDoc != null)
        {
            listenerRavenDoc.remove();
            listenerRavenDoc = null;
        }

        RavenDocument doc = editor.getDocument();
        if (doc != null)
        {
            listenerRavenDoc = new RavenDocumentWeakListener(this, doc);
            doc.addRavenDocumentListener(listenerRavenDoc);
        }
        
        updateDisplay();
    }

    private void updateDisplay()
    {
        SwingUtilities.invokeLater(
            new Runnable() {
                @Override
                public void run()
                {
                    updateDisplaySwing();
                }
            }
        );
    }
    
    private void updateDisplaySwing()
    {
        updating = true;

        RavenDocument doc = editor.getDocument();

        if (doc == null)
        {
            list_symbols.setListData(new Object[0]);
        }
        else
        {
            list_symbols.setListData(doc.getDocuments().toArray());
            list_symbols.setSelectedValue(doc.getCurDocument(), false);
        }

        updating = false;
    }

    @Override
    public void recentFilesChanged(EventObject evt)
    {
    }

    @Override
    public void documentChanged(EventObject evt)
    {
        updateDocument();
    }

    @Override
    public void documentSourceChanged(EventObject evt)
    {
    }
    
    @Override
    public void documentAdded(RavenDocumentEvent evt)
    {
        updateDisplay();
    }
    
    @Override
    public void documentRemoved(RavenDocumentEvent evt)
    {
        updateDisplay();
    }
    
    @Override
    public void currentDocumentChanged(RavenDocumentEvent evt)
    {
        if (updating)
        {
            return;
        }
        updateDisplay();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        list_symbols = new javax.swing.JList();
        jPanel1 = new javax.swing.JPanel();
        bn_create = new javax.swing.JButton();
        bn_rename = new javax.swing.JButton();
        bn_delete = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        list_symbols.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                list_symbolsValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(list_symbols);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        bn_create.setText("Create");
        bn_create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bn_createActionPerformed(evt);
            }
        });
        jPanel1.add(bn_create);

        bn_rename.setText("Rename");
        bn_rename.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bn_renameActionPerformed(evt);
            }
        });
        jPanel1.add(bn_rename);

        bn_delete.setText("Delete");
        bn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bn_deleteActionPerformed(evt);
            }
        });
        jPanel1.add(bn_delete);

        add(jPanel1, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void list_symbolsValueChanged(javax.swing.event.ListSelectionEvent evt)//GEN-FIRST:event_list_symbolsValueChanged
    {//GEN-HEADEREND:event_list_symbolsValueChanged
        if (updating)
        {
            return;
        }
        
        NodeDocument sym = (NodeDocument)list_symbols.getSelectedValue();
        RavenDocument doc = editor.getDocument();
        doc.setCurrentDocument(sym);
    }//GEN-LAST:event_list_symbolsValueChanged

    private void bn_createActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_bn_createActionPerformed
    {//GEN-HEADEREND:event_bn_createActionPerformed
        RavenDocument doc = editor.getDocument();
        if (doc == null)
        {
            return;
        }

//        String newName = doc.getUnusedDocumentName("symbol");
//                JOptionPane.showInputDialog(
//                this, "Create new symbol", newName);
//        if (newName == null)
//        {
//            return;
//        }

        NewDocumentWizard wiz = new NewDocumentWizard(editor);

        RavenWizardDialog dlg = new RavenWizardDialog(
                editor.getViewManager().getSwingRoot(), wiz);
        RavenSwingUtil.centerWindow(dlg);
        dlg.setVisible(true);

        NodeDocument sym = dlg.getNodeDocument();

        if (sym == null)
        {
            return;
        }
        
        String name = sym.getDocumentName();
        String newName = doc.getUnusedDocumentName(name);
        if (!newName.equals(name))
        {
            sym.setDocumentName(newName);
        }

        doc.addDocument(sym);
        
    }//GEN-LAST:event_bn_createActionPerformed

    private void bn_renameActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_bn_renameActionPerformed
    {//GEN-HEADEREND:event_bn_renameActionPerformed
        Object val = list_symbols.getSelectedValue();
        if (val == null)
        {
            return;
        }
        
        NodeDocument doc = (NodeDocument)val;
        String name = doc.getDocumentName();
        String newName = JOptionPane.showInputDialog(
                this, "Rename symbol", name == null ? "" : name);
        
        if (newName == null)
        {
            return;
        }
        
        doc.setDocumentName(newName);
        repaint();
    }//GEN-LAST:event_bn_renameActionPerformed

    private void bn_deleteActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_bn_deleteActionPerformed
    {//GEN-HEADEREND:event_bn_deleteActionPerformed
        RavenDocument doc = editor.getDocument();
        if (doc == null)
        {
            return;
        }

        Object val = list_symbols.getSelectedValue();
        if (val == null)
        {
            return;
        }
        
//System.err.println("Deleting");        
        NodeDocument sym = (NodeDocument)val;
//        int idx = doc.indexOfDocument(sym);
        doc.removeDocument(sym);

    }//GEN-LAST:event_bn_deleteActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bn_create;
    private javax.swing.JButton bn_delete;
    private javax.swing.JButton bn_rename;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList list_symbols;
    // End of variables declaration//GEN-END:variables

    //------------------------------------
    
    
    class Renderer extends JLabel implements ListCellRenderer
    {
        private static final long serialVersionUID = 1;

        public Renderer()
        {
            setOpaque(true);
        }

        @Override
        public Component getListCellRendererComponent(
                JList list, Object value, int index, 
                boolean isSelected, boolean cellHasFocus)
        {
            UIDefaults def = UIManager.getDefaults();
            setBackground(isSelected
                ? def.getColor("List.selectionBackground")
                : def.getColor("List.background"));
            
            NodeDocument doc = (NodeDocument)value;
            String name = doc.getDocumentName();
            setText(name == null ? "*" : name);
            return this;
        }
    }
}
