/*
 * Copyright 2011 Mark McKay
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * PaintLayoutLinearEditor.java
 *
 * Created on Jan 1, 2011, 4:10:11 AM
 */

package com.kitfox.raven.editor.paint;

import com.kitfox.game.control.color.PaintLayoutTexture;
import com.kitfox.rabbit.util.NumberText;

/**
 *
 * @author kitfox
 */
@Deprecated
public class PaintLayoutTextureEditor extends javax.swing.JPanel
{
    public static final String PROP_PAINT_LAYOUT = "paintLayout";
    private PaintLayoutTexture paintLayout;

    boolean updating = true;

    /** Creates new form PaintLayoutLinearEditor */
    public PaintLayoutTextureEditor()
    {
        initComponents();

        update();
    }

    private void update()
    {
        updating = true;

        if (paintLayout == null)
        {
            text_transX.setText("0");
            text_transY.setText("0");
            text_scaleX.setText("1");
            text_scaleY.setText("1");
            text_angle.setText("0");
            text_skewAngle.setText("90");
        }
        else
        {
            text_transX.setText("" + paintLayout.getTransX());
            text_transY.setText("" + paintLayout.getTransY());
            text_scaleX.setText("" + paintLayout.getScaleX());
            text_scaleY.setText("" + paintLayout.getScaleY());
            text_angle.setText("" + paintLayout.getAngle());
            text_skewAngle.setText("" + paintLayout.getSkewAngle());
        }

        updating = false;
    }

    private void commit()
    {
        float transX = NumberText.findFloat(text_transX.getText(), 0);
        float transY = NumberText.findFloat(text_transY.getText(), 0);
        float scaleX = NumberText.findFloat(text_scaleX.getText(), 1);
        float scaleY = NumberText.findFloat(text_scaleY.getText(), 1);
        float angle = NumberText.findFloat(text_angle.getText(), 0);
        float skewAngle = NumberText.findFloat(text_skewAngle.getText(), 90);

        setPaintLayout(new PaintLayoutTexture(transX, transY, scaleX, scaleY, angle, skewAngle));
    }

    /**
     * @return the paintLayout
     */
    public PaintLayoutTexture getPaintLayout()
    {
        return paintLayout;
    }

    /**
     * @param paintLayout the paintLayout to set
     */
    public void setPaintLayout(PaintLayoutTexture paintLayout)
    {
        PaintLayoutTexture old = this.paintLayout;
        this.paintLayout = paintLayout;
        update();
        firePropertyChange(PROP_PAINT_LAYOUT, old, paintLayout);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        text_transX = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        text_transY = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        text_scaleX = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        text_scaleY = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        text_skewAngle = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        text_angle = new javax.swing.JTextField();

        jLabel1.setText("Trans X");

        text_transX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_transXActionPerformed(evt);
            }
        });

        jLabel2.setText("Trans Y");

        text_transY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_transYActionPerformed(evt);
            }
        });

        jLabel3.setText("Scale X");

        text_scaleX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_scaleXActionPerformed(evt);
            }
        });

        jLabel4.setText("Scale Y");

        text_scaleY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_scaleYActionPerformed(evt);
            }
        });

        jLabel7.setText("Skew Angle");

        text_skewAngle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_skewAngleActionPerformed(evt);
            }
        });

        jLabel8.setText("Angle");

        text_angle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_angleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(text_transX, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(text_transY, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(text_scaleX, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(text_scaleY, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(text_angle, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(text_skewAngle, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(text_transX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(text_transY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(text_scaleX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(text_scaleY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(text_angle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(text_skewAngle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void text_transXActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_text_transXActionPerformed
    {//GEN-HEADEREND:event_text_transXActionPerformed
        commit();
    }//GEN-LAST:event_text_transXActionPerformed

    private void text_transYActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_text_transYActionPerformed
    {//GEN-HEADEREND:event_text_transYActionPerformed
        commit();
    }//GEN-LAST:event_text_transYActionPerformed

    private void text_scaleXActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_text_scaleXActionPerformed
    {//GEN-HEADEREND:event_text_scaleXActionPerformed
        commit();
    }//GEN-LAST:event_text_scaleXActionPerformed

    private void text_scaleYActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_text_scaleYActionPerformed
    {//GEN-HEADEREND:event_text_scaleYActionPerformed
        commit();
    }//GEN-LAST:event_text_scaleYActionPerformed

    private void text_skewAngleActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_text_skewAngleActionPerformed
    {//GEN-HEADEREND:event_text_skewAngleActionPerformed
        commit();
    }//GEN-LAST:event_text_skewAngleActionPerformed

    private void text_angleActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_text_angleActionPerformed
    {//GEN-HEADEREND:event_text_angleActionPerformed
        commit();
    }//GEN-LAST:event_text_angleActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField text_angle;
    private javax.swing.JTextField text_scaleX;
    private javax.swing.JTextField text_scaleY;
    private javax.swing.JTextField text_skewAngle;
    private javax.swing.JTextField text_transX;
    private javax.swing.JTextField text_transY;
    // End of variables declaration//GEN-END:variables

}
