/*
 * Copyright 2011 Mark McKay
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * PaintLayoutLinearEditor.java
 *
 * Created on Jan 1, 2011, 4:10:11 AM
 */

package com.kitfox.raven.editor.paint;

import com.kitfox.game.control.color.PaintLayoutRadial;
import com.kitfox.rabbit.util.NumberText;

/**
 *
 * @author kitfox
 */
public class PaintLayoutRadialEditor extends javax.swing.JPanel
{
    public static final String PROP_PAINT_LAYOUT = "paintLayout";
    private PaintLayoutRadial paintLayout;

    boolean updating = true;

    /** Creates new form PaintLayoutLinearEditor */
    public PaintLayoutRadialEditor()
    {
        initComponents();

        update();
    }

    private void update()
    {
        updating = true;

        if (paintLayout == null)
        {
            text_centerX.setText("0");
            text_centerY.setText("0");
            text_radiusX.setText("1");
            text_radiusY.setText("1");
            text_angle.setText("0");
            text_skewAngle.setText("90");
            text_focusX.setText("0");
            text_focusY.setText("0");
        }
        else
        {
            text_centerX.setText("" + paintLayout.getCenterX());
            text_centerY.setText("" + paintLayout.getCenterY());
            text_radiusX.setText("" + paintLayout.getRadiusX());
            text_radiusY.setText("" + paintLayout.getRadiusY());
            text_angle.setText("" + paintLayout.getAngle());
            text_skewAngle.setText("" + paintLayout.getSkewAngle());
            text_focusX.setText("" + paintLayout.getFocusX());
            text_focusY.setText("" + paintLayout.getFocusY());
        }

        updating = false;
    }

    private void commit()
    {
        float centerX = NumberText.findFloat(text_centerX.getText(), 0);
        float centerY = NumberText.findFloat(text_centerY.getText(), 0);
        float radiusX = NumberText.findFloat(text_radiusX.getText(), 1);
        float radiusY = NumberText.findFloat(text_radiusY.getText(), 1);
        float angle = NumberText.findFloat(text_angle.getText(), 0);
        float skewAngle = NumberText.findFloat(text_skewAngle.getText(), 90);
        float focusX = NumberText.findFloat(text_focusX.getText(), 0);
        float focusY = NumberText.findFloat(text_focusY.getText(), 0);

        setPaintLayout(new PaintLayoutRadial(centerX, centerY, radiusX, radiusY, angle, skewAngle, focusX, focusY));
    }

    /**
     * @return the paintLayout
     */
    public PaintLayoutRadial getPaintLayout()
    {
        return paintLayout;
    }

    /**
     * @param paintLayout the paintLayout to set
     */
    public void setPaintLayout(PaintLayoutRadial paintLayout)
    {
        PaintLayoutRadial old = this.paintLayout;
        this.paintLayout = paintLayout;
        update();
        firePropertyChange(PROP_PAINT_LAYOUT, old, paintLayout);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        text_centerX = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        text_centerY = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        text_radiusX = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        text_radiusY = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        text_focusX = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        text_focusY = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        text_skewAngle = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        text_angle = new javax.swing.JTextField();

        jLabel1.setText("Center X");

        text_centerX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_centerXActionPerformed(evt);
            }
        });

        jLabel2.setText("Center Y");

        text_centerY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_centerYActionPerformed(evt);
            }
        });

        jLabel3.setText("Radius X");

        text_radiusX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_radiusXActionPerformed(evt);
            }
        });

        jLabel4.setText("Radius Y");

        text_radiusY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_radiusYActionPerformed(evt);
            }
        });

        jLabel5.setText("Focus X");

        text_focusX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_focusXActionPerformed(evt);
            }
        });

        jLabel6.setText("Focus Y");

        text_focusY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_focusYActionPerformed(evt);
            }
        });

        jLabel7.setText("Skew Angle");

        text_skewAngle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_skewAngleActionPerformed(evt);
            }
        });

        jLabel8.setText("Angle");

        text_angle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_angleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(text_centerX, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(text_centerY, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(text_radiusX, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(text_radiusY, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(text_angle, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(text_skewAngle, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(text_focusX, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(text_focusY, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(text_centerX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(text_centerY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(text_radiusX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(text_radiusY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(text_angle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(text_skewAngle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(text_focusX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(text_focusY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void text_centerXActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_text_centerXActionPerformed
    {//GEN-HEADEREND:event_text_centerXActionPerformed
        commit();
    }//GEN-LAST:event_text_centerXActionPerformed

    private void text_centerYActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_text_centerYActionPerformed
    {//GEN-HEADEREND:event_text_centerYActionPerformed
        commit();
    }//GEN-LAST:event_text_centerYActionPerformed

    private void text_radiusXActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_text_radiusXActionPerformed
    {//GEN-HEADEREND:event_text_radiusXActionPerformed
        commit();
    }//GEN-LAST:event_text_radiusXActionPerformed

    private void text_radiusYActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_text_radiusYActionPerformed
    {//GEN-HEADEREND:event_text_radiusYActionPerformed
        commit();
    }//GEN-LAST:event_text_radiusYActionPerformed

    private void text_focusXActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_text_focusXActionPerformed
    {//GEN-HEADEREND:event_text_focusXActionPerformed
        commit();
    }//GEN-LAST:event_text_focusXActionPerformed

    private void text_focusYActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_text_focusYActionPerformed
    {//GEN-HEADEREND:event_text_focusYActionPerformed
        commit();
    }//GEN-LAST:event_text_focusYActionPerformed

    private void text_skewAngleActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_text_skewAngleActionPerformed
    {//GEN-HEADEREND:event_text_skewAngleActionPerformed
        commit();
    }//GEN-LAST:event_text_skewAngleActionPerformed

    private void text_angleActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_text_angleActionPerformed
    {//GEN-HEADEREND:event_text_angleActionPerformed
        commit();
    }//GEN-LAST:event_text_angleActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField text_angle;
    private javax.swing.JTextField text_centerX;
    private javax.swing.JTextField text_centerY;
    private javax.swing.JTextField text_focusX;
    private javax.swing.JTextField text_focusY;
    private javax.swing.JTextField text_radiusX;
    private javax.swing.JTextField text_radiusY;
    private javax.swing.JTextField text_skewAngle;
    // End of variables declaration//GEN-END:variables

}
