/*
 * Copyright 2011 Mark McKay
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * PaintLayoutLinearEditor.java
 *
 * Created on Jan 1, 2011, 4:10:11 AM
 */

package com.kitfox.raven.editor.paint;

import com.kitfox.game.control.color.PaintLayoutLinear;
import com.kitfox.rabbit.util.NumberText;

/**
 *
 * @author kitfox
 */
public class PaintLayoutLinearEditor extends javax.swing.JPanel
{
    public static final String PROP_PAINT_LAYOUT = "paintLayout";
    private PaintLayoutLinear paintLayout;

    boolean updating = true;

    /** Creates new form PaintLayoutLinearEditor */
    public PaintLayoutLinearEditor()
    {
        initComponents();

        update();
    }

    private void update()
    {
        updating = true;

        if (paintLayout == null)
        {
            text_startX.setText("0");
            text_startY.setText("0");
            text_endX.setText("1");
            text_endY.setText("0");
        }
        else
        {
            text_startX.setText("" + paintLayout.getStartX());
            text_startY.setText("" + paintLayout.getStartY());
            text_endX.setText("" + paintLayout.getEndX());
            text_endY.setText("" + paintLayout.getEndY());
        }

        updating = false;
    }

    private void commit()
    {
        float startX = NumberText.findFloat(text_startX.getText(), 0);
        float startY = NumberText.findFloat(text_startY.getText(), 0);
        float endX = NumberText.findFloat(text_endX.getText(), 1);
        float endY = NumberText.findFloat(text_endY.getText(), 0);

        setPaintLayout(new PaintLayoutLinear(startX, startY, endX, endY));
    }

    /**
     * @return the paintLayout
     */
    public PaintLayoutLinear getPaintLayout()
    {
        return paintLayout;
    }

    /**
     * @param paintLayout the paintLayout to set
     */
    public void setPaintLayout(PaintLayoutLinear paintLayout)
    {
        PaintLayoutLinear old = this.paintLayout;
        this.paintLayout = paintLayout;
        update();
        firePropertyChange(PROP_PAINT_LAYOUT, old, paintLayout);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        text_startX = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        text_startY = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        text_endX = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        text_endY = new javax.swing.JTextField();

        jLabel1.setText("Start X");

        text_startX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_startXActionPerformed(evt);
            }
        });

        jLabel2.setText("Start Y");

        text_startY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_startYActionPerformed(evt);
            }
        });

        jLabel3.setText("End X");

        text_endX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_endXActionPerformed(evt);
            }
        });

        jLabel4.setText("End Y");

        text_endY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_endYActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(text_startX, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(text_startY, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(text_endX, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(text_endY, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(text_startX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(text_startY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(text_endX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(text_endY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void text_startXActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_text_startXActionPerformed
    {//GEN-HEADEREND:event_text_startXActionPerformed
        commit();
    }//GEN-LAST:event_text_startXActionPerformed

    private void text_startYActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_text_startYActionPerformed
    {//GEN-HEADEREND:event_text_startYActionPerformed
        commit();
    }//GEN-LAST:event_text_startYActionPerformed

    private void text_endXActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_text_endXActionPerformed
    {//GEN-HEADEREND:event_text_endXActionPerformed
        commit();
    }//GEN-LAST:event_text_endXActionPerformed

    private void text_endYActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_text_endYActionPerformed
    {//GEN-HEADEREND:event_text_endYActionPerformed
        commit();
    }//GEN-LAST:event_text_endYActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField text_endX;
    private javax.swing.JTextField text_endY;
    private javax.swing.JTextField text_startX;
    private javax.swing.JTextField text_startY;
    // End of variables declaration//GEN-END:variables

}
