/*
 * Copyright 2011 Mark McKay
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * LayoutManagerPanel.java
 *
 * Created on Nov 15, 2010, 2:29:22 AM
 */

package com.kitfox.raven.editor;

import com.kitfox.xml.ns.raveneditorpreferences.ViewLayoutType;
import java.awt.Component;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.ListCellRenderer;
import javax.swing.UIDefaults;
import javax.swing.UIManager;

/**
 *
 * @author kitfox
 */
public class LayoutManagerPanel extends javax.swing.JPanel
{
    class LayoutRenderer extends JLabel implements ListCellRenderer
    {
        private static final long serialVersionUID = 1;

        public LayoutRenderer()
        {
            setOpaque(true);
        }

        @Override
        public Component getListCellRendererComponent(JList list, Object value, int index, boolean isSelected, boolean cellHasFocus)
        {
            if (value instanceof String)
            {
                //Empty lists will provide an empty string
                setText("");
                return this;
            }

            ViewLayoutType serv = (ViewLayoutType)value;
            UIDefaults def = UIManager.getDefaults();
            setBackground(isSelected
                ? def.getColor("List.selectionBackground")
                : def.getColor("List.background"));
            setText(serv == null ? "" : serv.getName());
            return this;
        }
    }



    final RavenViewManager viewManager;

    /** Creates new form LayoutManagerPanel */
    public LayoutManagerPanel(RavenViewManager viewManager)
    {
        this.viewManager = viewManager;
        initComponents();

        list_layouts.setCellRenderer(new LayoutRenderer());
        list_layouts.setListData(viewManager.getLayoutList().toArray());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        list_layouts = new javax.swing.JList();
        bn_delete = new javax.swing.JButton();

        jScrollPane1.setViewportView(list_layouts);

        bn_delete.setText("Delete");
        bn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bn_deleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                    .addComponent(bn_delete))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bn_delete)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bn_deleteActionPerformed
        Object[] values = list_layouts.getSelectedValues();

        for (int i = 0; i < values.length; ++i)
        {
            viewManager.removeLayout(((ViewLayoutType)values[i]).getName());
        }

        list_layouts.setListData(viewManager.getLayoutList().toArray());

    }//GEN-LAST:event_bn_deleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bn_delete;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList list_layouts;
    // End of variables declaration//GEN-END:variables

}
