/*
 * Copyright 2011 Mark McKay
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * ToolPaintLayoutSettings.java
 *
 * Created on Jan 1, 2011, 6:36:01 PM
 */

package com.kitfox.raven.editor.node.tools.common;

import com.kitfox.raven.editor.RavenEditor;
import com.kitfox.raven.editor.view.color.ColorPanel;
import java.awt.BorderLayout;

/**
 *
 * @author kitfox
 */
public class ToolPaintFloodSettings extends javax.swing.JPanel
{
    final RavenEditor editor;
    final ToolPaintFlood.Provider toolProvider;

    ColorPanel colorPanel;

    /** Creates new form ToolPaintLayoutSettings */
    public ToolPaintFloodSettings(RavenEditor editor, ToolPaintFlood.Provider toolProvider)
    {
        this.editor = editor;
        this.toolProvider = toolProvider;
        initComponents();

        colorPanel = new ColorPanel(editor);
        panel_colorArea.add(colorPanel, BorderLayout.CENTER);

        radio_fill.setSelected(!toolProvider.isStrokeMode());
        radio_stroke.setSelected(toolProvider.isStrokeMode());
    } 

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup_toolMode = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        radio_fill = new javax.swing.JRadioButton();
        radio_stroke = new javax.swing.JRadioButton();
        panel_colorArea = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        buttonGroup_toolMode.add(radio_fill);
        radio_fill.setSelected(true);
        radio_fill.setText("Fill Paint");
        radio_fill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_fillActionPerformed(evt);
            }
        });

        buttonGroup_toolMode.add(radio_stroke);
        radio_stroke.setText("Stroke Paint");
        radio_stroke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_strokeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radio_fill)
                    .addComponent(radio_stroke))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(radio_fill)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radio_stroke, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        panel_colorArea.setLayout(new java.awt.BorderLayout());
        jPanel1.add(panel_colorArea, java.awt.BorderLayout.SOUTH);

        add(jPanel1, java.awt.BorderLayout.NORTH);
    }// </editor-fold>//GEN-END:initComponents

    private void radio_fillActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_radio_fillActionPerformed
    {//GEN-HEADEREND:event_radio_fillActionPerformed
        toolProvider.setStrokeMode(false);
    }//GEN-LAST:event_radio_fillActionPerformed

    private void radio_strokeActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_radio_strokeActionPerformed
    {//GEN-HEADEREND:event_radio_strokeActionPerformed
        toolProvider.setStrokeMode(true);
    }//GEN-LAST:event_radio_strokeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup_toolMode;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel panel_colorArea;
    private javax.swing.JRadioButton radio_fill;
    private javax.swing.JRadioButton radio_stroke;
    // End of variables declaration//GEN-END:variables
}
