/*
 * Copyright 2011 Mark McKay
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * ToolPanSettings.java
 *
 * Created on Dec 11, 2010, 1:31:09 AM
 */

package com.kitfox.raven.editor.node.tools.common;

import com.kitfox.raven.editor.RavenEditor;
import com.kitfox.raven.editor.view.text.TextPanel;
import java.awt.BorderLayout;

/**
 *
 * @author kitfox
 */
public class ToolTextSettings extends javax.swing.JPanel
{
    RavenEditor editor;
    ToolText.Provider toolProvider;

    TextPanel panel;

    /** Creates new form ToolPanSettings */
    public ToolTextSettings(RavenEditor editor, ToolText.Provider toolProvider)
    {
        this.editor = editor;
        this.toolProvider = toolProvider;
        initComponents();

        panel = new TextPanel(editor);
        panel_textFeatures.add(panel, BorderLayout.CENTER);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_textFeatures = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        panel_textFeatures.setLayout(new java.awt.BorderLayout());
        add(panel_textFeatures, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panel_textFeatures;
    // End of variables declaration//GEN-END:variables

}
