/*
 * Copyright 2011 Mark McKay
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * NodeObjectPanel.java
 *
 * Created on Dec 1, 2010, 10:30:50 PM
 */

package com.kitfox.raven.util.tree.property;

import com.kitfox.raven.util.tree.NodeObject;
import java.util.ArrayList;

/**
 *
 * @author kitfox
 */
public class NodeObjectPanel extends javax.swing.JPanel
{
    boolean updating;

    NodeObject curNode;
    public static final String PROP_NODE = "node";

    /** Creates new form NodeObjectPanel */
    public NodeObjectPanel()
    {
        initComponents();
        
        combo_nodes.setRenderer(new NodeObjectCellRenderer());
    }

    public void setNode(NodeObject node)
    {
        NodeObject oldNode = curNode;
        curNode = node;
        combo_nodes.setSelectedItem(node);
        
        firePropertyChange(PROP_NODE, oldNode, node);
    }

    public void setNodes(ArrayList<NodeObject> list)
    {
        updating = true;

        Object sel = combo_nodes.getSelectedItem();

        combo_nodes.removeAllItems();
        for (NodeObject node: list)
        {
            combo_nodes.addItem(node);
        }

        combo_nodes.setSelectedItem(sel);

        updating = false;
    }

    public NodeObject getSelectedNode()
    {
        return (NodeObject)combo_nodes.getSelectedItem();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        combo_nodes = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();

        combo_nodes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_nodesActionPerformed(evt);
            }
        });

        jLabel1.setText("Node:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 311, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(combo_nodes, 0, 258, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 42, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combo_nodes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void combo_nodesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_nodesActionPerformed
        if (updating)
        {
            return;
        }

        setNode((NodeObject)combo_nodes.getSelectedItem());
}//GEN-LAST:event_combo_nodesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox combo_nodes;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
