/*
 * Copyright 2011 Mark McKay
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * SpriteTrackCustomEditor.java
 *
 * Created on Jul 9, 2009, 1:33:25 PM
 */

package com.kitfox.raven.util.tree.property;

import java.io.File;
import java.io.IOException;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileFilter;

/**
 *
 * @author kitfox
 */
public class ResourceCustomEditor extends javax.swing.JPanel
{
    private static final long serialVersionUID = 1;

    JFileChooser fileChooser = new JFileChooser();
    {
        FileFilter filter = new FileFilter()
        {
            @Override
            public boolean accept(File f) {
                return f.isDirectory() || f.getName().endsWith(".xml");
            }

            @Override
            public String getDescription() {
                return "Sprite resource (*.xml)";
            }
        };
        fileChooser.setFileFilter(filter);
        fileChooser.setCurrentDirectory(new File("work"));
    }

    final ResourceEditor editor;
    boolean updating;

    /** Creates new form SpriteTrackCustomEditor */
    public ResourceCustomEditor(ResourceEditor editor)
    {
        initComponents();
        this.editor = editor;
        try {
            updateFromEditor();
        } catch (URISyntaxException ex) {
            Logger.getLogger(ResourceCustomEditor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void updateFromEditor() throws URISyntaxException
    {
        updating = true;

        text_spriteUri.setText(editor.getAsText());

        updating = false;
    }

    private void browseForResource() throws URISyntaxException
    {
        File file = new File(editor.getAsText());
        fileChooser.setCurrentDirectory(file);

        int res = fileChooser.showOpenDialog(this);

        if (res != JFileChooser.APPROVE_OPTION)
        {
            return;
        }

        file = fileChooser.getSelectedFile();
        try {
//            editor.setAsText(file.getCanonicalPath());
            String path = file.toURI().toURL().toExternalForm();
            text_spriteUri.setText(path);
            editor.setAsText(path);
        } catch (IOException ex) {
            Logger.getLogger(ResourceCustomEditor.class.getName()).log(Level.SEVERE, null, ex);
        }
//        updateFromEditor();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        text_spriteUri = new javax.swing.JTextField();
        bn_browseSprite = new javax.swing.JButton();

        jLabel1.setText("Resource:");

        text_spriteUri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_spriteUriActionPerformed(evt);
            }
        });
        text_spriteUri.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                text_spriteUriFocusLost(evt);
            }
        });

        bn_browseSprite.setText("...");
        bn_browseSprite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bn_browseSpriteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(text_spriteUri, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bn_browseSprite)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(text_spriteUri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bn_browseSprite))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bn_browseSpriteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bn_browseSpriteActionPerformed
        try {
            browseForResource();
        } catch (URISyntaxException ex) {
            Logger.getLogger(ResourceCustomEditor.class.getName()).log(Level.SEVERE, null, ex);
        }
}//GEN-LAST:event_bn_browseSpriteActionPerformed

    private void text_spriteUriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_spriteUriActionPerformed
        if (updating)
        {
            return;
        }

        editor.setAsText(text_spriteUri.getText());

    }//GEN-LAST:event_text_spriteUriActionPerformed

    private void text_spriteUriFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_text_spriteUriFocusLost
        if (updating)
        {
            return;
        }

        editor.setAsText(text_spriteUri.getText());

    }//GEN-LAST:event_text_spriteUriFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bn_browseSprite;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField text_spriteUri;
    // End of variables declaration//GEN-END:variables

}
