/*
 * Copyright 2011 Mark McKay
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * HareDisplayFrame.java
 *
 * Created on Oct 6, 2010, 3:59:38 PM
 */

package com.kitfox.hare.testing;

import com.kitfox.rabbit.font.FontShape;
import com.kitfox.rabbit.font.svg.SimpleSVGFontLoader;
import com.kitfox.rabbit.parser.RabbitDocument;
import com.kitfox.rabbit.parser.RabbitDocumentPanel;
import com.kitfox.rabbit.parser.RabbitUniverseDom;
import java.awt.BorderLayout;
import java.io.File;
import java.net.MalformedURLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author kitfox
 */
public class HareDisplayFrame extends javax.swing.JFrame
{
    RabbitDocumentPanel panel = new RabbitDocumentPanel();

    /** Creates new form HareDisplayFrame */
    public HareDisplayFrame()
    {
        initComponents();

        try {

//            File file = new File("art/menu/BlurTest.svg");
            File file = new File("art/menu/InventoryMenu.svg");
//            File file = new File("art/menu/InventoryMenu2.svg");

            RabbitUniverseDom universe = new RabbitUniverseDom();
            {
//                Font font = new Font(Font.SERIF, Font.PLAIN, 1024);
//                SystemFontBuilder fb = new SystemFontBuilder(font);
//                FontShape fs = fb.build();

                FontShape fs = SimpleSVGFontLoader.loadFont(
                        getClass().getResourceAsStream("/Serif.svg"));

                universe.addFont(fs);

                universe.setDefaultFont(fs.getFontFace().getFontFamily());
            }

            RabbitDocument doc = universe.getDocument(file.toURI().toURL());
            panel.setDocument(doc);
        } catch (MalformedURLException ex) {
            Logger.getLogger(HareDisplayFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

        panel_docArea.add(panel, BorderLayout.CENTER);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_docArea = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel_docArea.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panel_docArea.setPreferredSize(new java.awt.Dimension(640, 480));
        panel_docArea.setLayout(new java.awt.BorderLayout());

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(panel_docArea, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(panel_docArea, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HareDisplayFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panel_docArea;
    // End of variables declaration//GEN-END:variables

}
