/*
 * Copyright 2011 Mark McKay
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * DockingTabbedPanel.java
 *
 * Created on Jan 12, 2011, 8:55:15 AM
 */

package com.kitfox.docking.test2;

import javax.swing.JComponent;

/**
 *
 * @author kitfox
 */
public class DockingTabbedPanel extends javax.swing.JPanel
{

    /** Creates new form DockingTabbedPanel */
    public DockingTabbedPanel()
    {
        initComponents();
    }

    public void addPanel(String title, JComponent comp)
    {
        tabbedPanel_main.addTab(title, comp);
        int idx = tabbedPanel_main.indexOfComponent(comp);
        tabbedPanel_main.setTabComponentAt(idx, new TabbedPaneTitle(this, comp));
    }

    public void selectTab(JComponent comp)
    {
        tabbedPanel_main.setSelectedComponent(comp);
    }

    public String getTabTitle(JComponent comp)
    {
        int idx = tabbedPanel_main.indexOfComponent(comp);
        return tabbedPanel_main.getTitleAt(idx);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPanel_main = new javax.swing.JTabbedPane();

        setLayout(new java.awt.BorderLayout());

        tabbedPanel_main.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        add(tabbedPanel_main, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane tabbedPanel_main;
    // End of variables declaration//GEN-END:variables

}
