/*
 * Copyright 2011 Mark McKay
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * TabbedPaneTitle.java
 *
 * Created on Jan 12, 2011, 8:06:49 AM
 */

package com.kitfox.docking.test2;

import javax.swing.JComponent;

/**
 *
 * @author kitfox
 */
public class TabbedPaneTitle extends javax.swing.JPanel
{
    final DockingTabbedPanel tabPanel;
    final JComponent comp;

    /** Creates new form TabbedPaneTitle */
    public TabbedPaneTitle(DockingTabbedPanel tabPanel, JComponent comp)
    {
        this.tabPanel = tabPanel;
        this.comp = comp;
        
        initComponents();
        label_title.setText(tabPanel.getTabTitle(comp));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_title = new javax.swing.JLabel();
        bn_float = new javax.swing.JButton();
        bn_maximize = new javax.swing.JButton();
        bn_minimize = new javax.swing.JButton();
        bn_close = new javax.swing.JButton();

        setOpaque(false);
        setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0));

        label_title.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label_title.setText("jLabel1");
        label_title.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 4));
        label_title.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_titleMouseClicked(evt);
            }
        });
        label_title.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                label_titleMouseDragged(evt);
            }
        });
        add(label_title);

        bn_float.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/float.png"))); // NOI18N
        bn_float.setBorderPainted(false);
        bn_float.setContentAreaFilled(false);
        bn_float.setMargin(new java.awt.Insets(0, 0, 0, 0));
        bn_float.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bn_floatActionPerformed(evt);
            }
        });
        add(bn_float);

        bn_maximize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/maximize.png"))); // NOI18N
        bn_maximize.setBorderPainted(false);
        bn_maximize.setContentAreaFilled(false);
        bn_maximize.setMargin(new java.awt.Insets(0, 0, 0, 0));
        bn_maximize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bn_maximizeActionPerformed(evt);
            }
        });
        add(bn_maximize);

        bn_minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/minimize.png"))); // NOI18N
        bn_minimize.setBorderPainted(false);
        bn_minimize.setContentAreaFilled(false);
        bn_minimize.setMargin(new java.awt.Insets(0, 0, 0, 0));
        bn_minimize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bn_minimizeActionPerformed(evt);
            }
        });
        add(bn_minimize);

        bn_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/close.png"))); // NOI18N
        bn_close.setBorderPainted(false);
        bn_close.setContentAreaFilled(false);
        bn_close.setMargin(new java.awt.Insets(0, 0, 0, 0));
        bn_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bn_closeActionPerformed(evt);
            }
        });
        add(bn_close);
    }// </editor-fold>//GEN-END:initComponents

    private void bn_floatActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_bn_floatActionPerformed
    {//GEN-HEADEREND:event_bn_floatActionPerformed
        System.err.println("Float");
    }//GEN-LAST:event_bn_floatActionPerformed

    private void bn_maximizeActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_bn_maximizeActionPerformed
    {//GEN-HEADEREND:event_bn_maximizeActionPerformed
        System.err.println("Max");
    }//GEN-LAST:event_bn_maximizeActionPerformed

    private void bn_minimizeActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_bn_minimizeActionPerformed
    {//GEN-HEADEREND:event_bn_minimizeActionPerformed
        System.err.println("Min");
    }//GEN-LAST:event_bn_minimizeActionPerformed

    private void bn_closeActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_bn_closeActionPerformed
    {//GEN-HEADEREND:event_bn_closeActionPerformed
        System.err.println("Close");
    }//GEN-LAST:event_bn_closeActionPerformed

    private void label_titleMouseDragged(java.awt.event.MouseEvent evt)//GEN-FIRST:event_label_titleMouseDragged
    {//GEN-HEADEREND:event_label_titleMouseDragged
        System.err.println("Dragging");
    }//GEN-LAST:event_label_titleMouseDragged

    private void label_titleMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_label_titleMouseClicked
    {//GEN-HEADEREND:event_label_titleMouseClicked
        tabPanel.selectTab(comp);
    }//GEN-LAST:event_label_titleMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bn_close;
    private javax.swing.JButton bn_float;
    private javax.swing.JButton bn_maximize;
    private javax.swing.JButton bn_minimize;
    private javax.swing.JLabel label_title;
    // End of variables declaration//GEN-END:variables

}
