/*
 * Copyright 2011 Mark McKay
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * GradientStylePanel.java
 *
 * Created on Sep 20, 2009, 2:34:20 AM
 */

package com.kitfox.raven.paint.common;

import com.kitfox.raven.paint.control.GradientStyleEditorPanel;
import java.awt.BorderLayout;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;

/**
 *
 * @author kitfox
 */
public class RavenPaintGradientCustomEditor extends javax.swing.JPanel
        implements PropertyChangeListener
{
    private static final long serialVersionUID = 0;

    GradientStyleEditorPanel panel = new GradientStyleEditorPanel();

    final RavenPaintGradientEditor ed;

    /** Creates new form GradientStylePanel */
    public RavenPaintGradientCustomEditor(RavenPaintGradientEditor ed)
    {
        initComponents();
        
        this.ed = ed;

        RavenPaintGradient value = ed.getValue();
        panel.setGradient(value.getStops());

        add(panel, BorderLayout.CENTER);
        panel.addPropertyChangeListener(
                GradientStyleEditorPanel.PROP_GRADIENT, this);
    }

    @Override
    public void propertyChange(PropertyChangeEvent evt)
    {
        ed.setValue(panel.getGradient());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
