/*
 * Copyright 2011 Mark McKay
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * StrokeStyleCustomEditor.java
 *
 * Created on Sep 17, 2009, 8:14:59 PM
 */

package com.kitfox.raven.paint.common;

import com.kitfox.coyote.shape.CyStroke;
import com.kitfox.coyote.shape.CyStrokeCap;
import com.kitfox.coyote.shape.CyStrokeJoin;
import com.kitfox.rabbit.util.NumberText;
import com.kitfox.raven.paint.RavenStroke;
import com.kitfox.raven.util.PropertyChangeWeakListener;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;

/**
 *
 * @author kitfox
 */
public class RavenStrokeCustomEditor extends javax.swing.JPanel implements PropertyChangeListener
{
    private static final long serialVersionUID = 1;

    PropertyChangeWeakListener listener;
    RavenStrokeEditor ed;

    boolean updating = true;

    /** Creates new form StrokeStyleCustomEditor */
    public RavenStrokeCustomEditor(RavenStrokeEditor ed)
    {
        this.ed = ed;
        initComponents();

        combo_cap.addItem(CyStrokeCap.BUTT);
        combo_cap.addItem(CyStrokeCap.ROUND);
        combo_cap.addItem(CyStrokeCap.SQUARE);

        combo_join.addItem(CyStrokeJoin.BEVEL);
        combo_join.addItem(CyStrokeJoin.MITER);
        combo_join.addItem(CyStrokeJoin.ROUND);

        listener = new PropertyChangeWeakListener(this, ed);
        ed.addPropertyChangeListener(listener);

        update();
    }

    public void update()
    {
        updating = true;

        RavenStroke ravenStroke = ed.getValue();
        if (ravenStroke == null)
        {
            ravenStroke = new RavenStroke();
        }

        CyStroke stroke = ravenStroke.getStroke();
        text_width.setText("" + stroke.getWidth());
        combo_cap.setSelectedItem(stroke.getCap());
        combo_join.setSelectedItem(stroke.getJoin());
        text_miterLimit.setText("" + stroke.getMiterLimit());
        float[] dashArray = stroke.getDashFloat();
        text_dash.setText(dashArray == null ? "" : NumberText.asString(dashArray, ","));
        text_dashPhase.setText("" + stroke.getDashOffset());

        updating = false;
    }

    public void export()
    {
        ed.setAsText(String.format("{width: %f; cap: %s; join: %s; miterLimit: %f; dash: (%s); dashPhase: %f}",
                NumberText.findFloat(text_width.getText(), 1),
                combo_cap.getSelectedItem().toString(),
                combo_join.getSelectedItem().toString(),
                NumberText.findFloat(text_miterLimit.getText(), 10),
                NumberText.cleanFloatArray(text_dash.getText(), ","),
                NumberText.findFloat(text_dashPhase.getText(), 0)));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        text_width = new javax.swing.JTextField();
        combo_cap = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        combo_join = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        text_miterLimit = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        text_dash = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        text_dashPhase = new javax.swing.JTextField();

        jLabel1.setText("Width");

        text_width.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_widthActionPerformed(evt);
            }
        });
        text_width.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                text_widthFocusLost(evt);
            }
        });

        combo_cap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_capActionPerformed(evt);
            }
        });

        jLabel2.setText("Cap");

        jLabel3.setText("Join");

        combo_join.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_joinActionPerformed(evt);
            }
        });

        jLabel4.setText("Miter Limit");

        text_miterLimit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_miterLimitActionPerformed(evt);
            }
        });
        text_miterLimit.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                text_miterLimitFocusLost(evt);
            }
        });

        jLabel5.setText("Dash");

        text_dash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_dashActionPerformed(evt);
            }
        });
        text_dash.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                text_dashFocusLost(evt);
            }
        });

        jLabel6.setText("Dash Phase");

        text_dashPhase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_dashPhaseActionPerformed(evt);
            }
        });
        text_dashPhase.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                text_dashPhaseFocusLost(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(text_width, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(combo_cap, 0, 214, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(combo_join, 0, 214, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(text_miterLimit, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(text_dash, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(text_dashPhase, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(text_width, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(combo_cap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(combo_join, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(text_miterLimit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(text_dash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(text_dashPhase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void text_widthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_widthActionPerformed
        export();
    }//GEN-LAST:event_text_widthActionPerformed

    private void text_widthFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_text_widthFocusLost
        export();
    }//GEN-LAST:event_text_widthFocusLost

    private void text_miterLimitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_miterLimitActionPerformed
        export();
    }//GEN-LAST:event_text_miterLimitActionPerformed

    private void text_miterLimitFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_text_miterLimitFocusLost
        export();
    }//GEN-LAST:event_text_miterLimitFocusLost

    private void text_dashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_dashActionPerformed
        export();
    }//GEN-LAST:event_text_dashActionPerformed

    private void text_dashFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_text_dashFocusLost
        export();
    }//GEN-LAST:event_text_dashFocusLost

    private void text_dashPhaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_dashPhaseActionPerformed
        export();
    }//GEN-LAST:event_text_dashPhaseActionPerformed

    private void text_dashPhaseFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_text_dashPhaseFocusLost
        export();
    }//GEN-LAST:event_text_dashPhaseFocusLost

    private void combo_capActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_capActionPerformed
        if (updating)
        {
            return;
        }

        export();
    }//GEN-LAST:event_combo_capActionPerformed

    private void combo_joinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_joinActionPerformed
        if (updating)
        {
            return;
        }

        export();
    }//GEN-LAST:event_combo_joinActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox combo_cap;
    private javax.swing.JComboBox combo_join;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField text_dash;
    private javax.swing.JTextField text_dashPhase;
    private javax.swing.JTextField text_miterLimit;
    private javax.swing.JTextField text_width;
    // End of variables declaration//GEN-END:variables

    @Override
    public void propertyChange(PropertyChangeEvent evt)
    {
        update();
    }

}
