/*
 * Copyright 2011 Mark McKay
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * StrokeStyleCustomEditor.java
 *
 * Created on Sep 17, 2009, 8:14:59 PM
 */

package com.kitfox.raven.paint;

import com.kitfox.raven.paint.control.PaintEditorPanel;
import com.kitfox.raven.util.tree.PropertyCustomEditor;
import com.kitfox.raven.util.tree.PropertyData;
import com.kitfox.raven.util.tree.PropertyDataInline;
import java.awt.BorderLayout;
import java.awt.Component;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;

/**
 *
 * @author kitfox
 */
public class RavenPaintCustomEditor extends javax.swing.JPanel
    implements PropertyCustomEditor, PropertyChangeListener
{
    private static final long serialVersionUID = 1;

    private final RavenPaintEditor editor;
    
    private PaintEditorPanel paintPanel = new PaintEditorPanel();
    
    PropertyData<RavenPaint> initValue;
    RavenPaint curValue;

    /** Creates new form StrokeStyleCustomEditor */
    public RavenPaintCustomEditor(RavenPaintEditor editor)
    {
        initComponents();

        this.editor = editor;
        initValue = editor.getValue();
        curValue = initValue.getValue(editor.getDocument());

        add(paintPanel, BorderLayout.CENTER);

        paintPanel.setPaint(curValue);
        paintPanel.addPropertyChangeListener(this);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    @Override
    public void propertyChange(PropertyChangeEvent evt)
    {
        if (evt.getSource() == paintPanel 
                && PaintEditorPanel.PROP_PAINT.equals(evt.getPropertyName()))
        {
            curValue = paintPanel.getPaint();
            editor.setValue(new PropertyDataInline(curValue), false);
        }
    }

    @Override
    public Component getCustomEditor()
    {
        return this;
    }

    @Override
    public void customEditorCommit()
    {
        editor.setValue(new PropertyDataInline(curValue), true);
    }

    @Override
    public void customEditorCancel()
    {
        editor.setValue(initValue, false);
    }
}
