/*
 * Copyright 2011 Mark McKay
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * PropertyCustomEditorPanel.java
 *
 * Created on Jul 21, 2009, 1:32:37 PM
 */

package com.kitfox.raven.editor.view.properties;

import com.kitfox.raven.editor.RavenEditorListener;
import com.kitfox.raven.util.SelectionListener;
import java.awt.BorderLayout;
import java.awt.Component;
import javax.swing.JDialog;

/**
 *
 * @author kitfox
 */
public class PropertyCustomEditorPanel extends javax.swing.JPanel
{
    private static final long serialVersionUID = 1;

    JDialog dialog;
    private boolean okay;

    /** Creates new form PropertyCustomEditorPanel
     * @param client
     * @param dialog
     */
    public PropertyCustomEditorPanel(Component client, JDialog dialog)
    {
        initComponents();

        this.dialog = dialog;

        panel_clientArea.add(client, BorderLayout.CENTER);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_clientArea = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        bn_okay = new javax.swing.JButton();
        bn_cancel = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        panel_clientArea.setLayout(new java.awt.BorderLayout());
        add(panel_clientArea, java.awt.BorderLayout.CENTER);

        bn_okay.setText("OK");
        bn_okay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bn_okayActionPerformed(evt);
            }
        });

        bn_cancel.setText("Cancel");
        bn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bn_cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bn_okay)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bn_cancel)
                .addContainerGap(125, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bn_okay)
                    .addComponent(bn_cancel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void bn_okayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bn_okayActionPerformed
        setOkay(true);
        dialog.setVisible(false);
        dialog.dispose();
    }//GEN-LAST:event_bn_okayActionPerformed

    private void bn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bn_cancelActionPerformed
        dialog.setVisible(false);
        dialog.dispose();
    }//GEN-LAST:event_bn_cancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bn_cancel;
    private javax.swing.JButton bn_okay;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panel_clientArea;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the okay
     */
    public boolean isOkay() {
        return okay;
    }

    /**
     * @param okay the okay to set
     */
    public void setOkay(boolean okay) {
        this.okay = okay;
    }

}
