/*
 * Copyright 2011 Mark McKay
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * ColorSliderPanel.java
 *
 * Created on Sep 19, 2009, 4:45:01 PM
 */

package com.kitfox.game.control.color;

/**
 *
 * @author kitfox
 */
public class ColorSliderPanel extends FieldSliderPanel<ColorChooserModel>
{
    private static final long serialVersionUID = 0;

    private ColorChooserModel model;

    /** Creates new form ColorSliderPanel */
    public ColorSliderPanel()
    {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @return the model
     */
    public ColorChooserModel getColorChooserModel()
    {
        return model;
    }

    /**
     * @param model the model to set
     */
    public void setColorChooserModel(ColorChooserModel model)
    {
        this.model = model;
        fieldPanel.setModel(model);
        updateColorModel();
    }

    @Override
    public void setColorField(ColorField colorField)
    {
        super.setColorField(colorField);
        updateColorModel();
    }

    private void updateColorModel()
    {
        if (model != null && getColorField() != null)
        {
            ColorSliderStopModel stopModel = new ColorSliderStopModel(getColorField(), model, getSide());
//            stopSliderPanel.setStopModel(stopModel);
            setStopModel(stopModel);
        }
        else
        {
            setStopModel(null);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
