/*
 * Copyright 2011 Mark McKay
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * StrokeStyleCustomEditor.java
 *
 * Created on Sep 17, 2009, 8:14:59 PM
 */

package com.kitfox.game.control.color;

import com.kitfox.game.control.color.MultipleGradientStops.Cycle;
import com.kitfox.game.control.color.MultipleGradientStops.Style;
import com.kitfox.raven.util.PropertyChangeWeakListener;
import java.awt.BorderLayout;
import java.awt.MultipleGradientPaint.ColorSpaceType;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;

/**
 *
 * @author kitfox
 */
@Deprecated
public class PaintStyleCustomEditor extends javax.swing.JPanel
        implements PropertyChangeListener
{
    private static final long serialVersionUID = 1;

    PropertyChangeWeakListener listener;
    final PaintStyleEditor ed;

    ColorCustomEditor colorPanel;
    MultipleGradientStyleCustomEditor gradientPanel;

    boolean updating = true;

    /** Creates new form StrokeStyleCustomEditor */
    public PaintStyleCustomEditor(PaintStyleEditor ed)
    {
        this.ed = ed;
        initComponents();

        colorPanel = new ColorCustomEditor(ed.colorEditor);
        gradientPanel = new MultipleGradientStyleCustomEditor(ed.gradientEditor);

        listener = new PropertyChangeWeakListener(this, ed);
        ed.addPropertyChangeListener(listener);

        update();
    }

    public void update()
    {
        updating = true;

        PaintStyle paint = ed.getValue();
        if (paint == null)
        {
//            paint = new Color(Color.WHITE.getRGB());
            paint = ColorStyle.WHITE;
        }

        panel_workArea.removeAll();
        if (paint instanceof ColorStyle)
        {
            panel_workArea.add(colorPanel, BorderLayout.CENTER);
        }
        else if (paint instanceof MultipleGradientStyle)
        {
            panel_workArea.add(gradientPanel, BorderLayout.CENTER);
        }

        updating = false;

        revalidate();
    }

//    public void export()
//    {
//        PaintStyle paint = ed.getValue();
//        ed.setAsText(paint.toCache().toString());
//    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        combo_type = new javax.swing.JComboBox();
        panel_workArea = new javax.swing.JPanel();

        jLabel1.setText("Type");

        combo_type.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Color", "Gradient" }));
        combo_type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_typeActionPerformed(evt);
            }
        });

        panel_workArea.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(combo_type, 0, 316, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(panel_workArea, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(combo_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_workArea, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void combo_typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_typeActionPerformed
        if (!updating)
        {
            String type = (String)combo_type.getSelectedItem();
            if ("Color".equals(type))
            {
                ed.setValue(ColorStyle.WHITE);
            }
            else if ("Gradient".equals(type))
            {
                MultipleGradientStops stops = new MultipleGradientStops(
                        new float[]{0, 1},
                        new ColorStyle[]{ColorStyle.BLACK, ColorStyle.WHITE},
                        Cycle.NO_CYCLE,
                        Style.LINEAR,
                        ColorSpaceType.SRGB);
                ed.setValue(stops);
            }
        }
    }//GEN-LAST:event_combo_typeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox combo_type;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panel_workArea;
    // End of variables declaration//GEN-END:variables

    @Override
    public void propertyChange(PropertyChangeEvent evt)
    {
        update();
    }

}
