/*
 * Copyright 2011 Mark McKay
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.kitfox.raven.editor.node.tools.common.shape;

import com.kitfox.raven.editor.RavenEditor;
import com.kitfox.raven.editor.node.scene.control.ColorPanel;
import java.awt.BorderLayout;

/**
 *
 * @author kitfox
 */
public class ToolPaintFloodSettings extends javax.swing.JPanel
{
    final RavenEditor editor;
    final ToolPaintFlood.Provider toolProvider;

    ColorPanel colorPanel;


    /**
     * Creates new form ToolPaintFloodSettings
     */
    public ToolPaintFloodSettings(RavenEditor editor, ToolPaintFlood.Provider toolProvider)
    {
        this.editor = editor;
        this.toolProvider = toolProvider;
        initComponents();

        colorPanel = new ColorPanel(editor);
        panel_colorArea.add(colorPanel, BorderLayout.CENTER);

        check_facePaint.setSelected(toolProvider.isFacePaint());
        check_edgePaint.setSelected(toolProvider.isStrokePaint());
        check_edgeShape.setSelected(toolProvider.isStrokeShape());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        panel_colorArea = new javax.swing.JPanel();
        check_facePaint = new javax.swing.JCheckBox();
        check_edgePaint = new javax.swing.JCheckBox();
        check_edgeShape = new javax.swing.JCheckBox();

        panel_colorArea.setLayout(new java.awt.BorderLayout());

        check_facePaint.setText("Face Paint");
        check_facePaint.setToolTipText("Fill faces with paint");
        check_facePaint.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                check_facePaintActionPerformed(evt);
            }
        });

        check_edgePaint.setText("Edge Paint");
        check_edgePaint.setToolTipText("Fill edges with paint");
        check_edgePaint.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                check_edgePaintActionPerformed(evt);
            }
        });

        check_edgeShape.setText("Edge Stroke");
        check_edgeShape.setToolTipText("Fill edges with stroke");
        check_edgeShape.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                check_edgeShapeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(check_facePaint)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(check_edgePaint)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(check_edgeShape)
                .addContainerGap(37, Short.MAX_VALUE))
            .addComponent(panel_colorArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(check_facePaint)
                    .addComponent(check_edgePaint)
                    .addComponent(check_edgeShape))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_colorArea, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void check_facePaintActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_check_facePaintActionPerformed
    {//GEN-HEADEREND:event_check_facePaintActionPerformed
        toolProvider.setFacePaint(check_facePaint.isSelected());
    }//GEN-LAST:event_check_facePaintActionPerformed

    private void check_edgePaintActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_check_edgePaintActionPerformed
    {//GEN-HEADEREND:event_check_edgePaintActionPerformed
        toolProvider.setStrokePaint(check_edgePaint.isSelected());
    }//GEN-LAST:event_check_edgePaintActionPerformed

    private void check_edgeShapeActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_check_edgeShapeActionPerformed
    {//GEN-HEADEREND:event_check_edgeShapeActionPerformed
        toolProvider.setStrokeShape(check_edgeShape.isSelected());
    }//GEN-LAST:event_check_edgeShapeActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox check_edgePaint;
    private javax.swing.JCheckBox check_edgeShape;
    private javax.swing.JCheckBox check_facePaint;
    private javax.swing.JPanel panel_colorArea;
    // End of variables declaration//GEN-END:variables
}
