/*
 * Copyright 2011 Mark McKay
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.kitfox.raven.editor.node.tools.common.shape;

import com.kitfox.raven.editor.RavenEditor;
import com.kitfox.raven.editor.node.scene.control.GraphDispPanel;
import com.kitfox.raven.editor.node.scene.control.SnappingPanel;

/**
 *
 * @author kitfox
 */
public class ToolCurveEditSettings extends javax.swing.JPanel
{
    RavenEditor editor;
    ToolCurveEdit.Provider prov;

    SnappingPanel snappingPanel;
    GraphDispPanel graphDispPanel;
    
    /**
     * Creates new form ToolPen2Settings
     */
    public ToolCurveEditSettings(RavenEditor editor, ToolCurveEdit.Provider prov)
    {
        this.editor = editor;
        this.prov = prov;
        initComponents();

        snappingPanel = new SnappingPanel(editor);
        panel_boxArea.add(snappingPanel);
        
        graphDispPanel = new GraphDispPanel(editor);
        panel_boxArea.add(graphDispPanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        panel_spacer = new javax.swing.JPanel();
        panel_boxArea = new javax.swing.JPanel();
        panel_colorArea = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        panel_spacer.setLayout(new java.awt.BorderLayout());
        add(panel_spacer, java.awt.BorderLayout.CENTER);

        panel_boxArea.setLayout(new javax.swing.BoxLayout(panel_boxArea, javax.swing.BoxLayout.Y_AXIS));

        panel_colorArea.setLayout(new java.awt.BorderLayout());
        panel_boxArea.add(panel_colorArea);

        add(panel_boxArea, java.awt.BorderLayout.NORTH);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panel_boxArea;
    private javax.swing.JPanel panel_colorArea;
    private javax.swing.JPanel panel_spacer;
    // End of variables declaration//GEN-END:variables
}
