/*
 * To change this template, choose Tools | Templates and open the template in
 * the editor.
 */
package com.kitfox.raven.movie.exporter;

import com.kitfox.raven.wizard.RavenWizardPage;
import java.awt.BorderLayout;
import java.awt.Component;

/**
 *
 * @author kitfox
 */
public class ExportMoviePanel extends javax.swing.JPanel
        implements RavenWizardPage
{
    public static final String PREF_FORMAT_SEQ = "formatSeq";
    public static final String PREF_FORMAT_FRAMES = "formatFrames";
    
    MovieExporterContext ctx;
    
    ExportMovieFramesPanel framesPanel;
    ExportMovieSeqPanel seqPanel;
    
    boolean updating = true;

    /**
     * Creates new form ExportMoviePanel
     */
    public ExportMoviePanel(MovieExporterContext ctx)
    {
        this.ctx = ctx;
        
        initComponents();

        framesPanel = new ExportMovieFramesPanel(ctx);
        seqPanel = new ExportMovieSeqPanel(ctx);
        
        updateFromContext();
    }

    private void updateFromContext()
    {
        updating = true;

        radio_formatSeq.setSelected(ctx.getFormat() == MovieExporterFormat.SEQ);
        radio_formatFrames.setSelected(ctx.getFormat() == MovieExporterFormat.FRAMES);

        panel_formatArea.removeAll();
        switch (ctx.getFormat())
        {
            case FRAMES:
                panel_formatArea.add(framesPanel, BorderLayout.CENTER);
                break;
            case SEQ:
                panel_formatArea.add(seqPanel, BorderLayout.CENTER);
                break;
        }
        
        updating = false;
        
        revalidate();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup_format = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        radio_formatSeq = new javax.swing.JRadioButton();
        radio_formatFrames = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        spinner_width = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        spinner_height = new javax.swing.JSpinner();
        panel_formatArea = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        buttonGroup_format.add(radio_formatSeq);
        radio_formatSeq.setText("Sequence");
        radio_formatSeq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_formatSeqActionPerformed(evt);
            }
        });

        buttonGroup_format.add(radio_formatFrames);
        radio_formatFrames.setSelected(true);
        radio_formatFrames.setText("Frames");
        radio_formatFrames.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_formatFramesActionPerformed(evt);
            }
        });

        jLabel1.setText("Width");

        spinner_width.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(640), Integer.valueOf(1), null, Integer.valueOf(1)));

        jLabel2.setText("jLabel2");

        spinner_height.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(480), Integer.valueOf(1), null, Integer.valueOf(1)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(radio_formatFrames)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radio_formatSeq))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spinner_width, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spinner_height, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(155, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radio_formatSeq)
                    .addComponent(radio_formatFrames))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(spinner_width, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(spinner_height, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.NORTH);

        panel_formatArea.setLayout(new java.awt.BorderLayout());
        add(panel_formatArea, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void radio_formatFramesActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_radio_formatFramesActionPerformed
    {//GEN-HEADEREND:event_radio_formatFramesActionPerformed
        ctx.setFormat(MovieExporterFormat.FRAMES);
        
    }//GEN-LAST:event_radio_formatFramesActionPerformed

    private void radio_formatSeqActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_radio_formatSeqActionPerformed
    {//GEN-HEADEREND:event_radio_formatSeqActionPerformed
        ctx.setFormat(MovieExporterFormat.SEQ);

    }//GEN-LAST:event_radio_formatSeqActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup_format;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panel_formatArea;
    private javax.swing.JRadioButton radio_formatFrames;
    private javax.swing.JRadioButton radio_formatSeq;
    private javax.swing.JSpinner spinner_height;
    private javax.swing.JSpinner spinner_width;
    // End of variables declaration//GEN-END:variables

    @Override
    public String getTitle()
    {
        return "Movie Exporter";
    }

    @Override
    public Component getComponent()
    {
        return this;
    }

}
